apiVersion: v1
entries:
  clipboard:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-03-01T20:17:40.512673548-05:00"
    dependencies:
    - name: hull
      repository: https://vidispine.github.io/hull
      version: 1.33.0
    description: Shared clipboard service with WebSocket sync
    digest: 604625f67919f2fc4a95833ded1cc1d71f342a66de6582ca5d6ab72b5df85f66
    name: clipboard
    type: application
    urls:
    - https://raw.githubusercontent.com/ConnorsApps/clipboard/main/helm/clipboard-1.0.1.tgz
    version: 1.0.1
  hull:
  - apiVersion: v2
    appVersion: "1.33"
    created: "2026-03-01T20:17:40.520817367-05:00"
    description: HULL - Helm Uniform Layer Library
    digest: 7e83d241684a93defd31f0311572a8c70d46dc3ae8395f199ac9ed5d8cee530f
    home: https://github.com/vidispine/hull
    icon: https://github.com/vidispine/hull/blob/gh-pages/hull.png?raw=true
    keywords:
    - hull
    - utility
    maintainers:
    - email: georgmartin.weber@bertelsmann.de
      name: georg weber
    - email: michael.baum@bertelsmann.de
      name: michael baum
    name: hull
    type: library
    urls:
    - https://raw.githubusercontent.com/ConnorsApps/clipboard/main/helm/charts/hull-1.33.0.tgz
    version: 1.33.0
generated: "2026-03-01T20:17:40.50387144-05:00"
